[project]
name = "canna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blackjax>=1.5",
    "corner>=2.2.3",
    "einops>=0.8.1",
    "equinox>=0.13.8",
    "jax[cuda]>=0.10.1",
    "jaxgb>=0.2.1",
    "jaxtyping>=0.3.2",
    "jexplore>=0.0.2",
    "lisaorbits>=3.0.3",
    "optax>=0.2.8",
    "tqdm>=4.67.1",
    "wdm-transform>=0.4.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "nbconvert>=7.17.1",
]
