"""LaTeX tables from the scorecards, written to paper/tables/*.tex.

Every number in the result tables is computed here from the files in paper/data, so a
table can be regenerated when they change. Conventions (scorecard.py):
width = 1.4826 MAD of the f0 draws in bins of 1/T_obs; found = width < 1 bin; widths and
offsets are medians over found sources, coverage and ranks over all sources in the band.
B finds almost nothing, so its widths and offsets are medians over every source narrower
than LOST_BINS instead. The MCMC tables come from lisa_checks/compare_mcmc.py's summaries.
"""

import numpy as np

import data
import style

BANDS = data.SNR_BANDS
TEX_BANDS = [r"$<15$", r"15--40", r"40--100", r"$\geq 100$"]

# what each XS model is, and its A100 cost (research log, section 3)
LADDER = [
    ("XS-1M", "uniform", "512", "1M", "const.", "10.8"),
    ("XS-late", "warp", "512", "1M", "const.", "10.9"),
    ("XS-late-768", "warp", "768", "1M", "const.", "16.6"),
    ("XS-late-cool", "warp", "512", "1.2M", "cooled", "10.9 + 2.2"),
    ("XS-late-768-cool", "warp", "768", "1.2M", "cooled", "16.6 + 3.6"),
]


def band(sc, k):
    a, b = BANDS[k]
    return (sc["snr"] >= a) & (sc["snr"] < b)


def max_position_offset(sc):
    coord = data.window_coordinate()[: sc["snr"].size]
    keep = (sc["snr"] >= 40) & (sc["width"] < 1) & (sc["width"] > 0)
    edges = np.linspace(-1, 1, 9)
    return max(abs(np.median(sc["offset"][keep & (coord >= a) & (coord < b)]))
               for a, b in zip(edges[:-1], edges[1:]))


def ladder():
    rows = []
    for run, clock, width, steps, lr, hours in LADDER:
        sc = data.scorecard(run)
        loud = band(sc, 3)
        lf = loud & (sc["width"] < 1)
        found = [np.mean(sc["width"][band(sc, k)] < 1) for k in range(3)]
        rows.append(
            f"{clock} & {width} & {steps} & {lr} & {np.median(sc['width'][lf]):.3f} & "
            f"{np.median(sc['width'][lf] / sc['ideal'][lf]):.0f} & "
            + " & ".join(f"{x:.2f}" for x in found)
            + f" & {sc['in68'][loud].mean():.2f} & {sc['in95'][loud].mean():.2f} & "
            f"{sc['rank'][loud].mean():.2f} & {max_position_offset(sc):.3f} & {hours} \\\\"
        )
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{llllcccccccccl}}
\toprule
& & & & \multicolumn{{2}}{{c}}{{loud $f_0$ width ($\rho\geq100$)}} & \multicolumn{{3}}{{c}}{{found fraction, $\rho$:}} & \multicolumn{{3}}{{c}}{{calibration, $\rho\geq 100$}} & bias & A100 \\
\cmidrule(lr){{5-6}} \cmidrule(lr){{7-9}} \cmidrule(lr){{10-12}}
clock & width & steps & lr & bins & $\times$ ideal & $<15$ & 15--40 & 40--100 & in68 & in95 & rank & [bins] & hours \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


def final_by_band(run="XS-late-768-cool"):
    sc = data.scorecard(run)
    rows = []
    for k in range(4):
        m = band(sc, k)
        f = m & (sc["width"] < 1)
        rows.append(
            f"{TEX_BANDS[k]} & {m.sum()} & {f.sum() / m.sum():.2f} & {np.median(sc['width'][f]):.3f} & "
            f"{np.median(sc['width'][f] / sc['ideal'][f]):.0f} & {np.median(sc['offset'][f]):+.3f} & "
            f"{sc['in68'][m].mean():.2f} & {sc['in95'][m].mean():.2f} & {sc['rank'][m].mean():.2f} \\\\"
        )
    m = np.ones_like(sc["snr"], bool)
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{lrcccrccc}}
\toprule
SNR $\rho$ & $n$ & found & width [bins] & $\times$ ideal & offset [bins] & in68 & in95 & rank \\
\midrule
{body}
\midrule
all & {m.sum()} & {np.mean(sc['width'] < 1):.2f} & & & & {sc['in68'].mean():.2f} & {sc['in95'].mean():.2f} & {sc['rank'].mean():.2f} \\
\bottomrule
\end{{tabular}}
"""


def numerics():
    """XS-late under different integrators and precisions, on matched sources."""
    base = data.scorecard("XS-late")
    variants = [
        ("bf16, A100, 32 RK4 steps (default)", "XS-late"),
        ("bf16, A100, 64 steps", "XS-late_ode64"),
        ("bf16, A100, 128 steps", "XS-late_ode128"),
        ("fp32, CPU, 32 steps", "XS-late_float32_cpu"),
        ("fp32, A100, autotune level 0", "XS-late_float32_gpu_at0"),
        ("fp32, A100, autotune level 3", "XS-late_float32_gpu_at3"),
    ]
    rows = []
    for name, key in variants:
        sc = data.scorecard(key)
        n = sc["snr"].size
        ref = {k: v[:n] for k, v in base.items() if np.ndim(v) == 1}
        assert np.allclose(sc["snr"], ref["snr"])
        loud = band(sc, 3)
        both = loud & (sc["width"] < 1) & (ref["width"] < 1) & (ref["width"] > 0)
        ratio = np.median(sc["width"][both] / ref["width"][both])
        found = [np.mean(sc["width"][band(sc, k)] < 1) for k in range(4)]
        rows.append(
            f"{name} & {n} & " + " & ".join(f"{x:.2f}" for x in found)
            + f" & {np.median(sc['width'][loud & (sc['width'] < 1)]):.3f} & {ratio:.3f} & "
            f"{sc['in68'][loud].mean():.2f} & {sc['in95'][loud].mean():.2f} \\\\"
        )
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{lrccccccccc}}
\toprule
& & \multicolumn{{4}}{{c}}{{found fraction, $\rho$:}} & \multicolumn{{2}}{{c}}{{$f_0$ width, $\rho\geq100$}} & \multicolumn{{2}}{{c}}{{$\rho\geq100$}} \\
\cmidrule(lr){{3-6}} \cmidrule(lr){{7-8}} \cmidrule(lr){{9-10}}
sampler & $n$ & $<15$ & 15--40 & 40--100 & $\geq100$ & bins & ratio & in68 & in95 \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


LOST_BINS = 50.0  # B: wider than this, a source is spread over the window (SNR < 10 only)
F0_THIRDS = [(1.0e-4, 4.9e-4, "0.1--0.49\\,mHz"), (4.9e-4, 2.4e-3, "0.49--2.4\\,mHz"),
             (2.4e-3, 1.2e-2, "2.4--12\\,mHz")]


def b_by_band(run="B-late"):
    sc = data.scorecard(run)
    kept = sc["width"] < LOST_BINS
    rows = []
    for k in range(4):
        m = band(sc, k)
        w = m & kept
        rows.append(
            f"{TEX_BANDS[k]} & {m.sum()} & {np.mean(sc['width'][m] < 1):.2f} & "
            f"{np.median(sc['width'][w]):.2f} & {np.median(sc['width'][w] / sc['ideal'][w]):.0f} & "
            f"{np.median(sc['offset'][w]):+.2f} & {sc['in68'][m].mean():.2f} & "
            f"{sc['in95'][m].mean():.2f} & {sc['rank'][m].mean():.2f} \\\\"
        )
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
% {np.sum(~kept)} sources wider than {LOST_BINS:.0f} bins (SNR {sc['snr'][~kept].min():.1f}-{sc['snr'][~kept].max():.1f}) are left out of the widths
\begin{{tabular}}{{lrcccrccc}}
\toprule
SNR $\rho$ & $n$ & found & width [bins] & $\times$ ideal & offset [bins] & in68 & in95 & rank \\
\midrule
{body}
\midrule
all & {sc['snr'].size} & {np.mean(sc['width'] < 1):.2f} & & & & {sc['in68'].mean():.2f} & {sc['in95'].mean():.2f} & {sc['rank'].mean():.2f} \\
\bottomrule
\end{{tabular}}
"""


def b_coordinate():
    """The loud f0 width in bins and in units of the flow coordinate x_f, XS against B."""
    rows = []
    for run, label, steps in [("XS-late", "XS, 512, constant lr", "1M"),
                              ("XS-late-cool", "XS, 512, cooled", "1.2M"),
                              ("XS-late-768-cool", "XS, 768, cooled (final)", "1.2M"),
                              ("B-late", "B, 512, cooled", "0.2M")]:
        sc = data.scorecard(run)
        loud = band(sc, 3)
        if run == "B-late":
            per_unit = data.b_coordinate()["bins_per_x"]
            m = loud & (sc["width"] < LOST_BINS)
        else:
            per_unit = np.full(sc["snr"].size, data.XS_BINS_PER_UNIT)
            m = loud & (sc["width"] < 1)
        units = sc["width"][m] / per_unit[m]
        rows.append(
            f"{label} & {steps} & {np.median(per_unit[loud]):.0f} & {np.mean(sc['width'][loud] < 1):.2f} & "
            f"{np.median(sc['width'][m]):.3g} & {np.median(sc['width'][m] / sc['ideal'][m]):.0f} & "
            f"{1e3 * np.median(units):.2f} & {1e3 * np.percentile(units, 25):.2f}--{1e3 * np.percentile(units, 75):.2f} \\\\"
        )
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{llrcccc c}}
\toprule
& & bins per & found & \multicolumn{{2}}{{c}}{{loud $f_0$ width}} & \multicolumn{{2}}{{c}}{{in units of $x_f$ [$10^{{-3}}$]}} \\
\cmidrule(lr){{5-6}} \cmidrule(lr){{7-8}}
model & steps & unit of $x_f$ & $\rho\geq100$ & bins & $\times$ ideal & median & IQR \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


def b_frequency(run="B-late"):
    sc, coord = data.scorecard(run), data.b_coordinate()
    f0 = coord["f0"]
    rows = []
    for lo, hi, label in F0_THIRDS:
        m = (f0 >= lo) & (f0 < hi)
        w = m & (sc["snr"] >= 40) & (sc["width"] < LOST_BINS)
        rows.append(
            f"{label} & {m.sum()} & {w.sum()} & {np.median(sc['width'][w]):.2f} & "
            f"{1e3 * np.median(sc['width'][w] / coord['bins_per_x'][w]):.2f} & "
            f"{np.median(np.abs(sc['offset'][w])):.2f} & {sc['in68'][m].mean():.2f} & {sc['in95'][m].mean():.2f} \\\\"
        )
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{lrrcccc c}}
\toprule
& & & \multicolumn{{3}}{{c}}{{$\rho\geq40$}} & & \\
\cmidrule(lr){{4-6}}
$f_0$ & $n$ & $n_{{\rho\geq40}}$ & width [bins] & width [$10^{{-3}}\,x_f$] & $|$offset$|$ [bins] & in68 & in95 \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


MCMC_WINDOWS = [(9, "loudest"), (5, "crowded")]
MCMC_COLUMNS = [r"$f_0$", r"$\Mc$", r"$\Amp$", r"$\alpha$", r"$\sin\delta$", r"$\psi$",
                r"$\cos\iota$", r"$\phi_0$"]


def mcmc_table():
    """Flow / MCMC width ratio per parameter, and the share of flow draws off the source."""
    rows = []
    for j, name in MCMC_WINDOWS:
        z = data.mcmc(j)
        for s in np.argsort(-z["snr"]):
            r = z[f"s{s}"]
            mark = "" if z[f"s{s}_in95"].all() else "$^\\ast$"
            ratio = lambda x: f"{x:.0f}" if x >= 10 else f"{x:.2f}"
            rows.append(f"{name} & {z['snr'][s]:.1f} & " + " & ".join(ratio(x) for x in r[1])
                        + f" & {100 * float(z[f's{s}_far']):.0f}\\%{mark} \\\\")
        rows.append("\\midrule")
    body = "\n".join(rows[:-1])
    head = " & ".join(MCMC_COLUMNS)
    return rf"""% generated by paper/scripts/tables.py from data/mcmc; do not edit by hand
\begin{{tabular}}{{lrccccccccr}}
\toprule
& & \multicolumn{{8}}{{c}}{{width, flow / MCMC}} & off \\
\cmidrule(lr){{3-10}}
window & SNR & {head} & $>1$ bin \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


def mcmc_checks():
    """The MCMC itself: its f0 width, Fisher against it, and the two seeds against each other."""
    rows = []
    for j, name in MCMC_WINDOWS:
        z = data.mcmc(j)
        for s in np.argsort(-z["snr"]):
            r = z[f"s{s}"]
            fisher = r[3][[0, 2, 3, 4, 5, 6, 7]]  # every parameter but the prior-dominated Mc
            rows.append(
                f"{name} & {z['snr'][s]:.1f} & {r[0][0]:.2g} & {r[3][0]:.2f} & "
                f"{fisher.min():.2f}--{fisher.max():.2f} & {np.max(np.abs(r[4] - 1)):.3f} & {r[5].max():.2f} \\\\"
            )
        rows.append("\\midrule")
    body = "\n".join(rows[:-1])
    return rf"""% generated by paper/scripts/tables.py from data/mcmc; do not edit by hand
\begin{{tabular}}{{lrccccc}}
\toprule
& & MCMC $f_0$ & \multicolumn{{2}}{{c}}{{width, Fisher / MCMC}} & \multicolumn{{2}}{{c}}{{seed 1 against seed 0}} \\
\cmidrule(lr){{4-5}} \cmidrule(lr){{6-7}}
window & SNR & width [bins] & $f_0$ & other & max $|$width ratio $-1|$ & max $W_1/\sigma$ \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


def detection_pairs():
    """Sources found by one model and not the other (for the text)."""
    pairs = [("XS-1M", "XS-late"), ("XS-late", "XS-late-768"), ("XS-late-768", "XS-late-768-cool"),
             ("XS-late-cool", "XS-late-768-cool"), ("XS-1M", "XS-late-768-cool")]
    lines = []
    for a, b in pairs:
        fa, fb = data.scorecard(a)["width"] < 1, data.scorecard(b)["width"] < 1
        lines.append(f"% found only by {a}: {np.sum(fa & ~fb)}, only by {b}: {np.sum(fb & ~fa)}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    style.TABLES.mkdir(exist_ok=True)
    for name, text in [("xs_ladder", ladder()), ("xs_final_by_band", final_by_band()),
                       ("xs_numerics", numerics()), ("xs_detection_pairs", detection_pairs()),
                       ("b_by_band", b_by_band()), ("b_coordinate", b_coordinate()),
                       ("b_frequency", b_frequency()), ("mcmc", mcmc_table()),
                       ("mcmc_checks", mcmc_checks())]:
        (style.TABLES / f"{name}.tex").write_text(text)
        print(f"--- {name}\n{text}")
