"""LaTeX tables from the scorecards, written to paper/tables/*.tex.

Every number in the XS result tables is computed here from the scorecard files, so a
table can be regenerated when a scorecard changes. Conventions (scorecard.py):
width = 1.4826 MAD of the f0 draws in bins of 1/T_obs; found = width < 1 bin; widths and
offsets are medians over found sources, coverage and ranks over all sources in the band.
"""

import numpy as np

import data
import style

BANDS = data.SNR_BANDS
TEX_BANDS = [r"$<15$", r"15--40", r"40--100", r"$\geq 100$"]

# what each XS model is, and its A100 cost (research log, section 3)
LADDER = [
    ("XS-1M", "uniform", "512", "1M", "const.", "10.8"),
    ("XS-late", "warp", "512", "1M", "const.", "10.9"),
    ("XS-late-768", "warp", "768", "1M", "const.", "16.6"),
    ("XS-late-cool", "warp", "512", "1.2M", "cooled", "10.9 + 2.2"),
    ("XS-late-768-cool", "warp", "768", "1.2M", "cooled", "16.6 + 3.6"),
]


def band(sc, k):
    a, b = BANDS[k]
    return (sc["snr"] >= a) & (sc["snr"] < b)


def max_position_offset(sc):
    coord = data.window_coordinate()[: sc["snr"].size]
    keep = (sc["snr"] >= 40) & (sc["width"] < 1) & (sc["width"] > 0)
    edges = np.linspace(-1, 1, 9)
    return max(abs(np.median(sc["offset"][keep & (coord >= a) & (coord < b)]))
               for a, b in zip(edges[:-1], edges[1:]))


def ladder():
    rows = []
    for run, clock, width, steps, lr, hours in LADDER:
        sc = data.scorecard(run)
        loud = band(sc, 3)
        lf = loud & (sc["width"] < 1)
        found = [np.mean(sc["width"][band(sc, k)] < 1) for k in range(3)]
        rows.append(
            f"{clock} & {width} & {steps} & {lr} & {np.median(sc['width'][lf]):.3f} & "
            f"{np.median(sc['width'][lf] / sc['ideal'][lf]):.0f} & "
            + " & ".join(f"{x:.2f}" for x in found)
            + f" & {sc['in68'][loud].mean():.2f} & {sc['in95'][loud].mean():.2f} & "
            f"{sc['rank'][loud].mean():.2f} & {max_position_offset(sc):.3f} & {hours} \\\\"
        )
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{llllcccccccccl}}
\toprule
& & & & \multicolumn{{2}}{{c}}{{loud $f_0$ width ($\rho\geq100$)}} & \multicolumn{{3}}{{c}}{{found fraction, $\rho$:}} & \multicolumn{{3}}{{c}}{{calibration, $\rho\geq 100$}} & bias & A100 \\
\cmidrule(lr){{5-6}} \cmidrule(lr){{7-9}} \cmidrule(lr){{10-12}}
clock & width & steps & lr & bins & $\times$ ideal & $<15$ & 15--40 & 40--100 & in68 & in95 & rank & [bins] & hours \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


def final_by_band(run="XS-late-768-cool"):
    sc = data.scorecard(run)
    rows = []
    for k in range(4):
        m = band(sc, k)
        f = m & (sc["width"] < 1)
        rows.append(
            f"{TEX_BANDS[k]} & {m.sum()} & {f.sum() / m.sum():.2f} & {np.median(sc['width'][f]):.3f} & "
            f"{np.median(sc['width'][f] / sc['ideal'][f]):.0f} & {np.median(sc['offset'][f]):+.3f} & "
            f"{sc['in68'][m].mean():.2f} & {sc['in95'][m].mean():.2f} & {sc['rank'][m].mean():.2f} \\\\"
        )
    m = np.ones_like(sc["snr"], bool)
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{lrcccrccc}}
\toprule
SNR $\rho$ & $n$ & found & width [bins] & $\times$ ideal & offset [bins] & in68 & in95 & rank \\
\midrule
{body}
\midrule
all & {m.sum()} & {np.mean(sc['width'] < 1):.2f} & & & & {sc['in68'].mean():.2f} & {sc['in95'].mean():.2f} & {sc['rank'].mean():.2f} \\
\bottomrule
\end{{tabular}}
"""


def numerics():
    """XS-late under different integrators and precisions, on matched sources."""
    base = data.scorecard("XS-late")
    variants = [
        ("bf16, A100, 32 RK4 steps (default)", "XS-late"),
        ("bf16, A100, 64 steps", "XS-late_ode64"),
        ("bf16, A100, 128 steps", "XS-late_ode128"),
        ("fp32, CPU, 32 steps", "XS-late_float32_cpu"),
        ("fp32, A100, autotune level 0", "XS-late_float32_gpu_at0"),
        ("fp32, A100, autotune level 3", "XS-late_float32_gpu_at3"),
    ]
    rows = []
    for name, key in variants:
        sc = data.scorecard(key)
        n = sc["snr"].size
        ref = {k: v[:n] for k, v in base.items() if np.ndim(v) == 1}
        assert np.allclose(sc["snr"], ref["snr"])
        loud = band(sc, 3)
        both = loud & (sc["width"] < 1) & (ref["width"] < 1) & (ref["width"] > 0)
        ratio = np.median(sc["width"][both] / ref["width"][both])
        found = [np.mean(sc["width"][band(sc, k)] < 1) for k in range(4)]
        rows.append(
            f"{name} & {n} & " + " & ".join(f"{x:.2f}" for x in found)
            + f" & {np.median(sc['width'][loud & (sc['width'] < 1)]):.3f} & {ratio:.3f} & "
            f"{sc['in68'][loud].mean():.2f} & {sc['in95'][loud].mean():.2f} \\\\"
        )
    body = "\n".join(rows)
    return rf"""% generated by paper/scripts/tables.py from the scorecards; do not edit by hand
\begin{{tabular}}{{lrccccccccc}}
\toprule
& & \multicolumn{{4}}{{c}}{{found fraction, $\rho$:}} & \multicolumn{{2}}{{c}}{{$f_0$ width, $\rho\geq100$}} & \multicolumn{{2}}{{c}}{{$\rho\geq100$}} \\
\cmidrule(lr){{3-6}} \cmidrule(lr){{7-8}} \cmidrule(lr){{9-10}}
sampler & $n$ & $<15$ & 15--40 & 40--100 & $\geq100$ & bins & ratio & in68 & in95 \\
\midrule
{body}
\bottomrule
\end{{tabular}}
"""


def detection_pairs():
    """Sources found by one model and not the other (for the text)."""
    pairs = [("XS-1M", "XS-late"), ("XS-late", "XS-late-768"), ("XS-late-768", "XS-late-768-cool"),
             ("XS-late-cool", "XS-late-768-cool"), ("XS-1M", "XS-late-768-cool")]
    lines = []
    for a, b in pairs:
        fa, fb = data.scorecard(a)["width"] < 1, data.scorecard(b)["width"] < 1
        lines.append(f"% found only by {a}: {np.sum(fa & ~fb)}, only by {b}: {np.sum(fb & ~fa)}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    style.TABLES.mkdir(exist_ok=True)
    for name, text in [("xs_ladder", ladder()), ("xs_final_by_band", final_by_band()),
                       ("xs_numerics", numerics()), ("xs_detection_pairs", detection_pairs())]:
        (style.TABLES / f"{name}.tex").write_text(text)
        print(f"--- {name}\n{text}")
